#!/system/bin/sh

set -e

NAME=dnscrypt-proxy
DAEMON=/system/xbin/$NAME
CONFIG_DIR=/etc/dnscrypt-proxy
CONFIG_FILE=$CONFIG_DIR/dnscrypt-proxy.toml
CACHE_DIR=/data/local/tmp/dnscrypt

PROP_STATE=$( getprop persist.privacy.tor )

if [ "$PROP_STATE" == "1" ]; then
	CONFIG_FILE=$CONFIG_DIR/dnscrypt-proxy-tor.toml
fi

if test ! -s "$CONFIG_FILE"; then
    exit 1
fi

if [ ! -d "$CACHE_DIR" ]; then
	mkdir -p -m 01755 "$CACHE_DIR"
fi

if [ ! -f "$CACHE_DIR"/public-resolvers.md ]; then
	cp "$CONFIG_DIR"/public-resolvers.md "$CACHE_DIR"/
	cp "$CONFIG_DIR"/public-resolvers.md.minisig "$CACHE_DIR"/
	chmod 644 "$CACHE_DIR"/public-resolvers.md
	chmod 644 "$CACHE_DIR"/public-resolvers.md.minisig
fi

if [ ! -f "$CACHE_DIR"/relays.md ]; then
	cp "$CONFIG_DIR"/relays.md "$CACHE_DIR"/
	cp "$CONFIG_DIR"/relays.md.minisig "$CACHE_DIR"/
	chmod 644 "$CACHE_DIR"/relays.md
	chmod 644 "$CACHE_DIR"/relays.md.minisig
fi

if [ ! -f "$CACHE_DIR"/odoh.md ]; then
        cp "$CONFIG_DIR"/odoh.md "$CACHE_DIR"/
        cp "$CONFIG_DIR"/odoh.md.minisig "$CACHE_DIR"/
        chmod 644 "$CACHE_DIR"/odoh.md
        chmod 644 "$CACHE_DIR"/odoh.md.minisig
fi

exec $DAEMON -config "$CONFIG_FILE"
