#!/system/bin/sh

set -e

NAME=dnscrypt-proxy
DAEMON=/system/xbin/$NAME
CONFIG_DIR=/etc/dnscrypt-proxy
CONFIG_FILE=$CONFIG_DIR/dnscrypt-proxy.toml

PROP_STATE=$( getprop persist.privacy.tor )

if [ "$PROP_STATE" == "1" ]; then
	CONFIG_FILE=$CONFIG_DIR/dnscrypt-proxy-tor.toml
fi

if test ! -s "$CONFIG_FILE"; then
    exit 1
fi

exec $DAEMON -config "$CONFIG_FILE"
